[directory]
truncation_length = 8
truncation_symbol = "…/"

[hostname]
disabled = false
# format = "@[$hostname]($style):"
format = ":"
ssh_only = false

[username]
format = "[$user]($style)"
show_always = true

